-- Table 1 gym
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Gym One 5', 'Calea Circumvalatiunii nr.9, Timisoara', 2010, 0755300800, 'https://www.gymone.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Fitness Planet', 'Strada Mures nr.12, Timisoara', 2012, 0789200888, 'https://www.lifestule-gym.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Gym One 3', 'Alea Studentiilor nr.15, Timisoara', 2014, 0735310808, 'https://www.gymone.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Next Fit', 'Strada Luminii nr.3, Timisoara', 2018, 0795300600, 'https://www.nextfit.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('World Class', 'Calea Sever Bocu nr.82, Timisoara', 2018, 0715300100, 'https://www.worldclass.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Smart Fit Studio', 'Bulevardul Cetatii nr.42, Timisoara', 2017, 0755300199, 'https://www.smartfit-studio.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Gym One 2', 'Strada Liviu Rebreanu nr. 100, Timisoara', 2013, 0731300800, 'https://www.gymone.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('XOX Gym', 'Calea Romanilor nr.13, Arad', 2010, 0722300130, 'https://www.XOX-Gym.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Gym One 4', 'Calea Aurel Vlaicu nr.12, Arad', 2011, 0781300819, 'https://www.gymone.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Ade Gym', 'Strada Libertatii nr.1, Vinga', 2017, 0751300800, 'https://www.ade-gym.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Extreme Fitness', 'Strada Mures nr.22, Timisoara', 2015, 0751501802, 'https://www.extremefitness.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Sala Iguana Fitness', 'Strada Iosefin nr.4, Timisoara', 2016, 0722301800, 'https://www.iguanafitness.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Dream Body', 'Strada Lucian Blaga nr.9, Timisoara', 2019, 0792310800, 'https://www.dreambody.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Fit Arena', 'Strada Unirii nr.5, Timisoara', 2012, 0765300801, 'https://www.fitarena.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Titan Gym', 'Bulevardul Republicii nr.10, Arad', 2014, 0721300982, 'https://www.titangym.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Power House', 'Strada Industriei nr.7, Timisoara', 2011, 0733300505, 'https://www.powerhouse.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Alpha Fitness', 'Calea Martirilor nr.34, Timisoara', 2016, 0752400102, 'https://www.alphafitness.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Red Gym', 'Strada Revolutiei nr.3, Arad', 2018, 0741300772, 'https://www.redgym.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Smart Fit Studio Arad', 'Bulevardul Revolutiei nr.69, Timisoara', 2017, 0755300199, 'https://www.smartfit-studio.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Spartan Gym', 'Aleea Sportivilor nr.22, Timisoara', 2019, 0738300900, 'https://www.spartangym.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Pulse Gym', 'Strada Mihai Viteazu nr.15, Arad', 2013, 0722200991, 'https://www.pulsegym.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Galaxy Fitness', 'Strada Dacia nr.5, Timisoara', 2015, 0756300602, 'https://www.galaxyfitness.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Oxygen Gym', 'Strada Victoriei nr.8, Arad', 2017, 0789200888, 'https://www.oxygengym.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Lifestyle Gym', 'Calea Aurel Vlaicu nr.62, Arad', 2012, 0789200888, 'https://www.lifestyle-gym.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Body Fit Timisoara', 'Calea Aradului nr.13, Timisoara', 2020, 0789200888, 'https://www.bodyfitgym.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Clasic Gym Arad', 'Strada Unirii nr. 25, Arad', 2019, 0732200800, 'https://www.clasic-gym-arad.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Kratoos God`s Gym', 'Strada Martirilor nr. 7, Arad', 2019, 0753200605, 'https://www.ironfit.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Pulse Gym Arad', 'Calea Dorobantilor nr. 45, Arad', 2020, 0743200550, 'https://www.pulsegym.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('FitLab', 'Strada Calea Sagului nr. 6, Arad', 2018, 0735400708, 'https://www.fitlab.ro');
INSERT INTO gym (name, adress, established_year, contact_number, website) values ('Stay Fit', 'Strada Gheorgheni nr. 10, Timisoara', 2022, 0763300900, 'https://www.stay-fit.ro');

-- Table 2 employees 
INSERT INTO employees (name, age, position, contact_number) values ('Popa Alexandru', 28, 'receptionist', '0731279810');
INSERT INTO employees (name, age, position, contact_number) values ('Ionescu Maria', 52, 'janitor', '0745123456');
INSERT INTO employees (name, age, position, contact_number) values ('Georgescu Diana', 39, 'manager', '0765432187');
INSERT INTO employees (name, age, position, contact_number) values ('Tudor Dan', 32, 'maintenance technician', '0790123456');
INSERT INTO employees (name, age, position, contact_number) values ('Luca Bianca', 25, 'receptionist', '0719988776');
INSERT INTO employees (name, age, position, contact_number) values ('Dumitru Andreea', 39, 'janitor', '0723987654');
INSERT INTO employees (name, age, position, contact_number) values ('Florea Marius', 39, 'manager', '0712233445');
INSERT INTO employees (name, age, position, contact_number) values ('Serban Loredana', 21, 'receptionist', '0756677889');
INSERT INTO employees (name, age, position, contact_number) values ('Andreescu Vlad', 44, 'maintenance technician', '0733221144');
INSERT INTO employees (name, age, position, contact_number) values ('Voicu Ioana', 35, 'janitor', '0723344556');
INSERT INTO employees (name, age, position, contact_number) values ('Vasile Radu', 40, 'manager', '0711223344');
INSERT INTO employees (name, age, position, contact_number) values ('Gheorghe Raul', 31, 'receptionist', '0721122334');
INSERT INTO employees (name, age, position, contact_number) values ('Grigorescu Alex', 39, 'maintenance technician', '0705544332');
INSERT INTO employees (name, age, position, contact_number) values ('Nistor Andrei', 39, 'janitor', '0706655443');
INSERT INTO employees (name, age, position, contact_number) values ('Chirila Ramona', 28, 'manager', '0745566778');
INSERT INTO employees (name, age, position, contact_number) values ('Barbu Victor', 39, 'maintenance technician', '0701234567');
INSERT INTO employees (name, age, position, contact_number) values ('Oprea Alina', 42, 'janitor', '0745678901');
INSERT INTO employees (name, age, position, contact_number) values ('Constantin Mihai', 27, 'receptionist', '0723456789');
INSERT INTO employees (name, age, position, contact_number) values ('Popa Georgiana', 34, 'manager', '0756789012');
INSERT INTO employees (name, age, position, contact_number) values ('Radu Bogdan', 29, 'maintenance technician', '0712345678');
INSERT INTO employees (name, age, position, contact_number) values ('Ilie Raluca', 27, 'receptionist', '0766677888');
INSERT INTO employees (name, age, position, contact_number) values ('Matei Simona', 48, 'janitor', '0788123456');
INSERT INTO employees (name, age, position, contact_number) values ('Dobre Nicoleta', 32, 'receptionist', '0732145789');
INSERT INTO employees (name, age, position, contact_number) values ('Ciobanu Răzvan', 50, 'manager', '0788997766');
INSERT INTO employees (name, age, position, contact_number) values ('Petrescu Adina', 49, 'janitor', '0722344556');
INSERT INTO employees (name, age, position, contact_number) values ('Dinu Cristian', 30, 'receptionist', '0798765432');
INSERT INTO employees (name, age, position, contact_number) values ('Enache Florin', 45, 'maintenance technician', '0709876543');
INSERT INTO employees (name, age, position, contact_number) values ('Marin Sorin', 38, 'janitor', '0787654321');
INSERT INTO employees (name, age, position, contact_number) values ('Toma Eugen', 36, 'manager', '0725566778');
INSERT INTO employees (name, age, position, contact_number) values ('Popan Ana', 24, 'receptionist', '0713922119');

-- Table 3 facilities 
INSERT INTO facilities (name, additional_cost, facility_status) values ('Powerlifting Area', false, 'available');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Basketball Court', true, 'under maintenance');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Nutritional Counselling', true, 'available');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Café Area', true, 'available');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Kids Play Area', true, 'under maintenance');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Tanning Booth', true, 'available');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Cycling Room', true, 'available');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Yoga Studio', true, 'available');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Massage Room', true, 'available');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Sauna', true, 'available');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Virtual Classes', true, 'under maintenance');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Steam Room', true, 'under maintenance');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Boxing Area', true, 'available');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Personal Training', true, 'available');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Climbing Wall', true, 'under maintenance');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Running Track', false, 'available');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Table Tennis', false, 'available');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Wi-Fi Access', false, 'available');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Locker Rooms', false, 'available');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Outdoor Track', false, 'available');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Stretching Area', false, 'available');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Racquetball Court', true, 'available');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Dance Studio', true, 'available');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Hydrotherapy', true, 'available');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Swimming Pool', true, 'under maintenance');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Georgiana Wi-Fi Access', false, 'available');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Pilates Studio', true, 'under maintenance');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Zumba Studio', true, 'available');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Boxing Ring', true, 'under maintenance');
INSERT INTO facilities (name, additional_cost, facility_status) values ('Squash Court', true, 'available');

-- Table 4 products 
INSERT INTO products (name) values ('Protein Shake');
INSERT INTO products (name) values ('Pre-Workout Supplement');
INSERT INTO products (name) values ('BCAA');
INSERT INTO products (name) values ('Creatine');
INSERT INTO products (name) values ('Whey Protein');
INSERT INTO products (name) values ('Energy Drink');
INSERT INTO products (name) values ('L-Glutamine');
INSERT INTO products (name) values ('Vitamins & Minerals');
INSERT INTO products (name) values ('Meal Replacement Bar');
INSERT INTO products (name) values ('Hydration Tablets');
INSERT INTO products (name) values ('Post-Workout Recovery Drink');
INSERT INTO products (name) values ('Resistance Bands');
INSERT INTO products (name) values ('Yoga Mat');
INSERT INTO products (name) values ('Foam Roller');
INSERT INTO products (name) values ('Jump Rope');
INSERT INTO products (name) values ('Gym Gloves');
INSERT INTO products (name) values ('Weight Lifting Belt');
INSERT INTO products (name) values ('Gym Shoes');
INSERT INTO products (name) values ('Sports Water Bottle');
INSERT INTO products (name) values ('Massage Gun');
INSERT INTO products (name) values ('Collagen Supplements');
INSERT INTO products (name) values ('Amino Acids');
INSERT INTO products (name) values ('Fat Burner Supplement');
INSERT INTO products (name) values ('Resistance Bands');
INSERT INTO products (name) values ('Towel');
INSERT INTO products (name) values ('Protein Bar');
INSERT INTO products (name) values ('Healthy Snack Pack');
INSERT INTO products (name) values ('Smart Scale');
INSERT INTO products (name) values ('Stretching Strap');
INSERT INTO products (name) values ('Gym Bag');

-- Table 5 equipment 
INSERT INTO equipment (name, category, condition) values ('Deadlift Platform', 'Powerlifting', 'excellent');
INSERT INTO equipment (name, category, condition) values ('Squat Rack', 'Powerlifting', 'good');
INSERT INTO equipment (name, category, condition) values ('T-Bar Row', 'Bodybuilding', 'excellent');
INSERT INTO equipment (name, category, condition) values ('Dumbbells', 'Bodybuilding', 'good');
INSERT INTO equipment (name, category, condition) values ('IPF Calibrated Weight Plates', 'Powerlifting', 'good');
INSERT INTO equipment (name, category, condition) values ('Leg Press Machine', 'Bodybuilding', 'good');
INSERT INTO equipment (name, category, condition) values ('Lat Pulldown Machine', 'Bodybuilding', 'good');
INSERT INTO equipment (name, category, condition) values ('Cable Machine', 'Bodybuilding', 'good');
INSERT INTO equipment (name, category, condition) values ('EZ Curl Bar', 'BodyBuilding', 'excellent');
INSERT INTO equipment (name, category, condition) values ('Safety Squat Bar', 'Powerlifting', 'good');
INSERT INTO equipment (name, category, condition) values ('Hip Thrust Machine', 'Bodybuilding', 'excellent');
INSERT INTO equipment (name, category, condition) values ('Hammer Strength Machine', 'Bodybuilding', 'good');
INSERT INTO equipment (name, category, condition) values ('Smith Machine', 'Bodybuilding', 'good');
INSERT INTO equipment (name, category, condition) values ('Belt Squat Machine', 'Bodybuilding', 'excellent'); 
INSERT INTO equipment (name, category, condition) values ('Leg Curl Machine', 'Bodybuilding', 'good');
INSERT INTO equipment (name, category, condition) values ('Chest Press Machine', 'Bodybuilding', 'excellent');
INSERT INTO equipment (name, category, condition) values ('Incline Bench Press Machine', 'Bodybuilding', 'good');
INSERT INTO equipment (name, category, condition) values ('Glute Ham Developer', 'Bodybuilding', 'good');
INSERT INTO equipment (name, category, condition) values ('Deadlift Bar', 'Powerlifting', 'excellent');
INSERT INTO equipment (name, category, condition) values ('Vertical Leg Press Machine', 'Bodybuilding', 'excellent');
INSERT INTO equipment (name, category, condition) values ('Trap Bar', 'Powerlifting', 'excellent');
INSERT INTO equipment (name, category, condition) values ('Arm Curl Machine', 'Bodybuilding', 'good');
INSERT INTO equipment (name, category, condition) values ('Seated Abductor Machine', 'Bodybuilding', 'good');
INSERT INTO equipment (name, category, condition) values ('Pull-up Bar', 'Bodybuilding', 'excellent');
INSERT INTO equipment (name, category, condition) values ('Preacher Curl Bench', 'Bodybuilding', 'excellent');
INSERT INTO equipment (name, category, condition) values ('Leg Extension Machine', 'Bodybuilding', 'good');
INSERT INTO equipment (name, category, condition) values ('Seated Row Machine', 'Bodybuilding', 'good');
INSERT INTO equipment (name, category, condition) values ('Calf Raise Machine', 'Bodybuilding', 'excellent');
INSERT INTO equipment (name, category, condition) values ('Lying Leg Curl Machine', 'Bodybuilding', 'good');
INSERT INTO equipment (name, category, condition) values ('Abdominal Crunch Machine', 'Bodybuilding', 'excellent');

-- Table 6 tainer 
INSERT INTO trainer (name, age, phone, experience_years) values ('Popa Alexandru', 32, '0723123456', 7);
INSERT INTO trainer (name, age, phone, experience_years) values ('Popescu Mihai', 22, '0734123456', 2);
INSERT INTO trainer (name, age, phone, experience_years) values ('Iliescu Andrei', 32, '0745123456', 10);
INSERT INTO trainer (name, age, phone, experience_years) values ('Dumitrescu George', 30, '0756123456', 6);
INSERT INTO trainer (name, age, phone, experience_years) values ('Vasile Cristian', 33, '0767123456', 8);
INSERT INTO trainer (name, age, phone, experience_years) values ('Stoica Daniel', 20, '0778123456', 1);
INSERT INTO trainer (name, age, phone, experience_years) values ('Munteanu Ionut', 29, '0789123456', 5);
INSERT INTO trainer (name, age, phone, experience_years) values ('Georgescu Radu', 34, '0790123456', 9);
INSERT INTO trainer (name, age, phone, experience_years) values ('Toma Lucian', 31, '0701123456', 6);
INSERT INTO trainer (name, age, phone, experience_years) values ('Popescu Raluca', 27, '0735123456', 3);
INSERT INTO trainer (name, age, phone, experience_years) values ('Iliescu Elena', 36, '0746123456', 11);
INSERT INTO trainer (name, age, phone, experience_years) values ('Stoica Vlad', 25, '0757123456', 2);
INSERT INTO trainer (name, age, phone, experience_years) values ('Georgescu Marian', 38, '0768123456', 10);
INSERT INTO trainer (name, age, phone, experience_years) values ('Popa Gabriela', 30, '0779123456', 4);
INSERT INTO trainer (name, age, phone, experience_years) values ('Vasile Florin', 31, '0780123456', 6);
INSERT INTO trainer (name, age, phone, experience_years) values ('Dumitrescu Simona', 34, '0791123456', 7);
INSERT INTO trainer (name, age, phone, experience_years) values ('Toma Alina', 28, '0702123456', 3);
INSERT INTO trainer (name, age, phone, experience_years) values ('Iliescu Bogdan', 37, '0713123456', 12);
INSERT INTO trainer (name, age, phone, experience_years) values ('Munteanu Maria', 22, '0724123456', 3);
INSERT INTO trainer (name, age, phone, experience_years) values ('Popescu Nicolae', 35, '0735123456', 5);
INSERT INTO trainer (name, age, phone, experience_years) values ('Dumitrescu Ana', 31, '0746123456', 5);
INSERT INTO trainer (name, age, phone, experience_years) values ('Vasile Ioana', 32, '0757123456', 6);
INSERT INTO trainer (name, age, phone, experience_years) values ('Toma Iulian', 28, '0768123456', 4);
INSERT INTO trainer (name, age, phone, experience_years) values ('Popa Mihai', 25, '0779123456', 3);
INSERT INTO trainer (name, age, phone, experience_years) values ('Iliescu Bogdan', 30, '0780123456', 7);
INSERT INTO trainer (name, age, phone, experience_years) values ('Munteanu Andrei', 22, '0791123456', 1);
INSERT INTO trainer (name, age, phone, experience_years) values ('Popescu Florina', 23, '0702123456', 2);
INSERT INTO trainer (name, age, phone, experience_years) values ('Stoica Paul', 31, '0713123456', 6);
INSERT INTO trainer (name, age, phone, experience_years) values ('Bunea Alexandru', 37, '0724123456', 12);
INSERT INTO trainer (name, age, phone, experience_years) values ('Toma Mihai', 34, '0735123456', 8);

-- Table 7 class 
INSERT INTO class (name, duration, schedule, trainer_id) values ('Bodybuilding Basics', 60, 'Monday, Tuesday, Thursday, Friday - 16:00', 1);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Cardio Blast', 45, 'Tuesday - 17:30', 2);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Powerlifting Fundamentals', 75, 'Monday, Tuesday, Thursday, Friday - 18:00', 3);
INSERT INTO class (name, duration, schedule, trainer_id) values ('HIIT for Beginners', 30, 'Friday - 19:00', 4);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Strength Training', 60, 'Friday - 16:30', 5);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Endurance Training', 45, 'Monday - 17:00', 6);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Yoga for Flexibility', 60, 'Tuesday - 18:30', 7);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Pilates Core', 50, 'Wednesday - 16:30', 8);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Upper Body Strength', 60, 'Thursday - 19:30', 9);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Lower Body Workout', 60, 'Friday - 17:30', 10);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Stretch and Relax', 40, 'Monday - 19:00', 11);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Cardio Kickboxing', 50, 'Tuesday - 16:30', 12);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Strength and Power', 70, 'Wednesday - 19:30', 13);
INSERT INTO class (name, duration, schedule, trainer_id) values ('CrossFit Challenge', 60, 'Thursday - 16:00', 14);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Zumba Fitness', 45, 'Friday - 19:00', 15);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Full Body Circuit', 60, 'Monday - 18:30', 16);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Leg Day Power', 75, 'Tuesday - 16:00', 17);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Back to Basics', 60, 'Wednesday - 19:00', 18);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Advanced Strength Training', 90, 'Thursday - 17:00', 19);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Core Strengthening', 50, 'Friday - 18:00', 20);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Boxing for Fitness', 60, 'Monday - 17:30', 21);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Power Yoga', 60, 'Tuesday - 18:00', 22);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Muscle Toning', 50, 'Wednesday - 20:00', 23);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Strength Endurance', 70, 'Thursday - 18:00', 24);
INSERT INTO class (name, duration, schedule, trainer_id) values ('HIIT Intensity', 30, 'Friday - 16:00', 25);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Weight Loss Bootcamp', 45, 'Monday - 18:00', 26);
INSERT INTO class (name, duration, schedule, trainer_id) values ('BoxFit Challenge', 60, 'Tuesday - 16:30', 27);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Advanced Powerlifting', 75, 'Monday, Tuesday, Thursday, Friday - 18:00', 28);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Cardio Burn', 45, 'Thursday - 20:00', 29);
INSERT INTO class (name, duration, schedule, trainer_id) values ('Strength and Conditioning', 70, 'Friday - 17:00', 30);

-- Table 8 members 
INSERT INTO members (name, age, join_year, phone) values ('Heciko Raul', 26, 2022, 0751513066);
INSERT INTO members (name, age, join_year, phone) values ('Cutean Raul', 21, 2023, 0751513067);
INSERT INTO members (name, age, join_year, phone) values ('Picu Daniel', 22, 2021, 0751513068);
INSERT INTO members (name, age, join_year, phone) values ('Ciobanu Sebastian', 19, 2020, 0751513069);
INSERT INTO members (name, age, join_year, phone) values ('Nistor Paul', 23, 2022, 0751513070);
INSERT INTO members (name, age, join_year, phone) values ('Stanescu Elena', 21, 2023, 0751513071);
INSERT INTO members (name, age, join_year, phone) values ('Georgescu Luca', 25, 2022, 0751513072);
INSERT INTO members (name, age, join_year, phone) values ('Odina Andreea', 20, 2021, 0751513073);
INSERT INTO members (name, age, join_year, phone) values ('Vitan Andrei', 24, 2022, 0751513074);
INSERT INTO members (name, age, join_year, phone) values ('Rotariu Alexandru', 23, 2023, 0751513075);
INSERT INTO members (name, age, join_year, phone) values ('Tunseanu Sorin Catalin', 23, 2021, 0751513076);
INSERT INTO members (name, age, join_year, phone) values ('Vlad Roxana', 21, 2023, 0751513077);
INSERT INTO members (name, age, join_year, phone) values ('Popescu Adrian', 27, 2020, 0751513078);
INSERT INTO members (name, age, join_year, phone) values ('Radulescu Ioana', 23, 2021, 0751513079);
INSERT INTO members (name, age, join_year, phone) values ('Zamfir Doru', 29, 2023, 0751513080);
INSERT INTO members (name, age, join_year, phone) values ('Lazar Carmen', 24, 2020, 0751513081);
INSERT INTO members (name, age, join_year, phone) values ('Stoica Bogdan', 20, 2022, 0751513082);
INSERT INTO members (name, age, join_year, phone) values ('Curea Marius', 22, 2021, 0751513083);
INSERT INTO members (name, age, join_year, phone) values ('Petrache Ilie', 19, 2022, 0751513084);
INSERT INTO members (name, age, join_year, phone) values ('Voinescu Larisa', 26, 2023, 0751513085);
INSERT INTO members (name, age, join_year, phone) values ('Enescu Alin', 25, 2020, 0751513086);
INSERT INTO members (name, age, join_year, phone) values ('Munteanu Adriana', 22, 2022, 0751513087);
INSERT INTO members (name, age, join_year, phone) values ('Balcescu Lucian', 23, 2021, 0751513088);
INSERT INTO members (name, age, join_year, phone) values ('Tunseanu Cristian', 24, 2023, 0751513089);
INSERT INTO members (name, age, join_year, phone) values ('Smarandache Mihaela', 25, 2022, 0751513090);
INSERT INTO members (name, age, join_year, phone) values ('Nica Alexandru', 28, 2023, 0751513091);
INSERT INTO members (name, age, join_year, phone) values ('Balan Simona', 21, 2020, 0751513092);
INSERT INTO members (name, age, join_year, phone) values ('Pavel Irina', 19, 2021, 0751513093);
INSERT INTO members (name, age, join_year, phone) values ('Chiriac Florin', 22, 2022, 0751513094);
INSERT INTO members (name, age, join_year, phone) values ('Mesan Oana', 23, 2020, 0751513095);

-- Table 9 members_goals
INSERT INTO members_goals (goal_type, progress, members_id) values ('Compete in powerlifting', 'very good progress', 1);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Build more muscle', 'good', 2);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Lose weight', 'in progress', 3);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Build more muscle', 'excellent', 4);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Compete in bodybuilding', 'good', 5);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Compete in bodybuilding', 'average', 6);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Run a marathon', 'good progress', 7);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Improve posture', 'very good progress', 8);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Lose weight', 'in progress', 9);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Gain strength', 'excellent', 10);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Improve posture', 'good', 11);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Increase stamina', 'good progress', 12);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Achieve a lean physique', 'in progress', 13);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Achieve personal best in squat', 'excellent progress', 14);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Increase chest size', 'good progress', 15);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Build a six-pack', 'good', 16);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Increase stamina', 'excellent', 17);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Compete in triathlon', 'in progress', 18);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Increase grip strength', 'good progress', 19);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Achieve a muscle-up', 'good progress', 20);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Improve sprint speed', 'excellent', 21);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Build a six-pack', 'in progress', 22);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Compete in powerlifting', 'good', 23);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Lose fat percentage', 'very good progress', 24);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Increase bench press weight', 'excellent', 25);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Increase deadlift', 'good progress', 26);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Achieve better cardio fitness', 'good progress', 27);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Build more muscle', 'average', 28);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Build muscle and overall health', 'average', 29);
INSERT INTO members_goals (goal_type, progress, members_id) values ('Increase stamina', 'average', 30);

-- Table 10 subscription
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Full Time Fitness', '08.01.2025','07.02.2025', true, 1, 1);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Student Plan', '01.01.2025', '31.12.2025', true, 2, 2);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Good Morning Fitness', '01.06.2024', '01.07.2024', false, 3, 3);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Full Access', '12.05.2024', '11.06.2024', false, 4, 4);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Student plan', '01.01.2024', '31.01.2024', false, 5, 5);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Weekend Fitness', '01.02.2025', '28.02.2025', true, 6, 6);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Full Time Fitness', '01.01.2025','31.01.2025', true, 7, 7);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Student Plan', '21.05.2024', '20.06.2024', false, 8, 8);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Good Morning Fitness', '08.01.2024','07.02.2024', false, 9, 9);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Full Fitness', '01.01.2025', '31.01.2025', true, 10, 10);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Premium Access', '01.02.2024', '28.02.2024', false, 11, 11);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Evening Plan', '25.01.2025', '24.02.2025', true, 12, 12);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Weekend Fitness', '01.01.2025', '31.12.2025', true, 13, 13);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Full Access', '01.06.2024', '31.07.2024', false, 14, 14);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Exclusive Plan', '21.12.2024', '20.01.2025', false, 15, 15);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Student plan', '01.01.2025', '31.01.2025', true, 16, 16);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Full fitness', '04.04.2023', '03.05.2023', false, 17, 17);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Morning Fitness', '01.02.2025', '01.03.2025', true, 18, 18);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Weekend Plan', '12.12.2024', '11.01.2025', false, 19, 19);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Full Access', '18.01.2025', '17.02.2025', true, 20, 20);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Student Plan', '03.01.2025', '02.02.2025', true, 21, 21);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Morning Plan', '15.03.2025', '14.04.2024', false, 22, 22);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Full Fitness', '01.01.2025', '31.12.2025', true, 23, 23);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Student Plan', '04.04.2024', '03.05.2024', false, 24, 24);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Full Access', '01.01.2025', '31.01.2025', true, 25, 25);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Weekend Fitness', '13.01.2024', '12.02.2024', true, 26, 26);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Corporate Access', '28.07.2023', '27.08.2023', false, 27, 27);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Exclusive Plan', '23.01.2025', '22.02.2025', true, 28, 28);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Full Time Fitness', '16.05.2024', '15.06.2024', false, 29, 29);
INSERT INTO subscription (subscription_type, start_date, end_date, status, gym_id, members_id) values ('Morning Fitness', '01.01.2025', '31.12.2025', true, 30, 30);

-- Table 11 feedback
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (10, '28.02.2024', 1, 1, 1, 1);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (9, '27.05.2023', 2, 2, 2, 2);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (8, '05.12.2024', 3, 3, 3, 3);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (9, '19.09.2024', 4, 4, 4, 4);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (5, '14.06.2024', 5, 5, 5, 5);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (8, '25.07.2023', 6, 6, 6, 6);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (9, '07.03.2024', 7, 7, 7, 7);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (7, '29.12.2024', 8, 8, 8, 8);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (9, '13.01.2025', 9, 9, 9, 9);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (8, '22.12.2024', 10, 10, 10, 10);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (10, '20.02.2024', 11, 11, 11, 11);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (9, '03.12.2024', 12, 12, 12, 12);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (8, '17.07.2024', 13, 13, 13, 13);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (7, '30.12.2024', 14, 14, 14, 14);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (6, '24.01.2023', 15, 15, 15, 15);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (8, '11.12.2024', 16, 16, 16, 16);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (9, '06.07.2024', 17, 17, 17, 17);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (10, '02.10.2024', 18, 18, 18, 18);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (8, '15.05.2023', 19, 19, 19, 19);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (7, '02.01.2025', 20, 20, 20, 20);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (6, '18.12.2024', 21, 21, 21, 21);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (9, '10.07.2023', 22, 22, 22, 22);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (8, '23.09.2024', 23, 23, 23, 23);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (7, '12.01.2025', 24, 24, 24, 24);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (6, '02.11.2023', 25, 25, 25, 25);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (9, '04.01.2025', 26, 26, 26, 26);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (8, '02.01.2025', 27, 27, 27, 27);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (10, '21.12.2024', 28, 28, 28, 28);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (7, '09.10.2024', 29, 29, 29, 29);
INSERT INTO feedback (rating, feedback_date, members_id, gym_id, class_id, trainer_id) values (6, '01.12.2023', 30, 30, 30, 30);
